spring:
  application:
    name: basic
  datasource:
    url: jdbc:h2:mem:testdb
    password:
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        security: trace
